### PR TITLE
Create new tasks for found bugs and UI/UX issues

### PR DESCRIPTION
**Pull request by ThomasMPont**
## Overview

Here I am, creating a blank PR again, but I need a place for my work to be reviewed.

For a couple hours, I've tested the app's basic functionality and created tasks to record any issues I found. I heavily underestimated the amount of issues I would encounter. While creating tasks to fix these issues, I had to look into bugs and rethink design decisions, which took me a while.

## Review

To review this PR, I would expect you to read over all the new tasks and,
- confirm the existence of the bugs.
- confirm the relevance of the UI/UX issues.
- ensure task descriptions are clear.
- criticize any design decisions I might have enforced in task specifications.

## Issues

Here are the new tasks that were opened. In order of what I personally should be fixed first.

### Major bugs

These bugs must be fixed ASAP.
- [Fix crash while adding users](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90106141)
- [Rethink edit profile confirmation](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90101222)
- [Fix the login screen to be skipped when logged in](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90101585&issue=Signify-epfl%7Csignify-app%7C367)
- [Fix the back button](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=89985698&issue=Signify-epfl%7Csignify-app%7C362)

### Minor bugs

We should consider fixing these.
- [Fix blinking when navigating to the current screen](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90101270)
- [Fix dark mode](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105806)
- [Fix recognized signs from lingering in the practice screen](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90106781)

### Confusing design

These designs decisions might confuse users.
- [Rethink the challenge navigation graph](https://github.com/orgs/Signify-epfl/projects/2/views/1?filterQuery=chall&pane=issue&itemId=90119353&issue=Signify-epfl%7Csignify-app%7C380)
- [Make the language switch a dropdown list](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90104516)
- [Improve quiz completion feedback](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105595)
- [Augment the "try hand signs" screen to give live feedback on accuracy](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90104103)

### Unpleasant design

These elements don't match the app's theme or conventions set by today's popular apps.
- [Logout button](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90101590)
- [Rethink edit profile confirmation](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90101222)
- [Change the friends list colors](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90119458)
- [Separate dictionary elements](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90119645)
- [Fix dictionary image outlines](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105288)
- [Add dictionary images](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105314)
- [Redesign the exercise difficulty buttons](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90101286)
- [Improve the username field](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90119113)
- [Set the system bar's color](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105448)
- [Fix the settings screen's layout](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105714)
- [Rethink the profile screen's layout](https://github.com/orgs/Signify-epfl/projects/2/views/1?filterQuery=profile&pane=issue&itemId=90105660)

## Next steps

These new tasks should easily cover next sprint's work.

The app's backend functionality has not been extensively tested yet. There probably remains bugs to iron out in there.

We can never test the app enough.

### CODE REVIEW

**Review by NBCCF025 — CHANGES_REQUESTED** [review]
## General
You did a great job by testing the app UI and behaviour. In the following review, if a task is not mentioned that means I approve it and think it was well described.

## Task to Discuss
**Minor bugs:**
- [Fix dark mode](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105806)
I don't agree with this task, I think if we let the user change the color theme, it is correct to have a default one that is the same for everyone. Especially to avoid the current problem we are facing with the language, so that we don't have inconsistency with the button in the SettingScreen.

- [Fix recognized signs from lingering in the practice screen](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90106781)
This is a valid task, that I am currently working on (I just wanted to let you know that I have seen this and the change is already done in my branch).

**Confusion design:**
- [Make the language switch a dropdown list](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90104516)
This is a valid task that should be completed to have English as the default language of the app to be able to change it like we can do for the color theme. The current problem I am facing is that the language is set by default to the one used by the system, so for me it is French. However, in the settings the toggle is by default in English which give inconsistency.

**Unpleasant design:**
- [Change the friends list colors](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90119458)
I don't think this is a necessary task as the color of the app are not the one from figma. I would even say that the color in the friendsListScreen match correctly with the other screens.

**Figma:**
A lot of the task require changes in the figma design and I agree with that, I am just giving you my concern about it as I don't think I could manage the figma alone with all the work planned. You will find below some of the task concerned by figma changes.
- [Rethink the challenge navigation graph](https://github.com/orgs/Signify-epfl/projects/2/views/1?filterQuery=chall&pane=issue&itemId=90119353&issue=Signify-epfl%7Csignify-app%7C380)
- [Improve quiz completion feedback](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105595)
- [Augment the practice screen to give live feedback on accuracy](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90104103)

**Comment by ThomasMPont** [comment]
@NBCCF025 
> - [Fix dark mode](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90105806)
I don't agree with this task, I think if we let the user change the color theme, it is correct to have a default one that is the same for everyone. Especially to avoid the current problem we are facing with the language, so that we don't have inconsistency with the button in the SettingScreen.

Fair enough, I've deleted it.

**Comment by ThomasMPont** [comment]
[Fix recognized signs from lingering in the practice screen](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90106781)
This is a valid task, that I am currently working on (I just wanted to let you know that I have seen this and the change is already done in my branch).

Nice, thanks for linking my task to your PR.

**Comment by ThomasMPont** [comment]
> - [Make the language switch a dropdown list](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90104516)
This is a valid task that should be completed to have English as the default language of the app to be able to change it like we can do for the color theme. The current problem I am facing is that the language is set by default to the one used by the system, so for me it is French. However, in the settings the toggle is by default in English which give inconsistency.

I've added fixing this bug to that task's specifications.

**Comment by ThomasMPont** [comment]
> - [Change the friends list colors](https://github.com/orgs/Signify-epfl/projects/2/views/1?pane=issue&itemId=90119458)
I don't think this is a necessary task as the color of the app are not the one from figma. I would even say that the color in the friendsListScreen match correctly with the other screens.

I've added to the specifications of these tasks that Figma should be updated with their changes. We should block any PRs until the Figma design is updated to match any changes to the app's UI.

**Comment by ThomasMPont** [comment]
> Figma:
A lot of the task require changes in the figma design and I agree with that, I am just giving you my concern about it as I don't think I could manage the figma alone with all the work planned. You will find below some of the task concerned by figma changes.

I've added to the specifications of these tasks that Figma should be updated with their changes. We should block any PRs in general unless the Figma design is updated to match their changes.

**Comment by ThomasMPont** [comment]
@NBCCF025
I've tried to address your concerns. Do you see anything else?

**Review by NBCCF025 — APPROVED** [review]
For me everything is good now, well done!

**Pull request merged**
