### PR TITLE
New feature : update profile picture 

### PR DESCRIPTION
**Pull request by nada-ezziti**
This pull request introduces the functionality to manage profile pictures in the SettingsScreen. Users can now:
- Choose a profile picture from their gallery.
- Delete the profile picture, reverting to a default placeholder.
__________

**New Components :** 

_Composable: UserProfilePicture_
- Displays the user's profile picture if available or a default placeholder when no image is set.
- Supports interaction for editing or deleting the profile picture.

_Function: uriToFile_
- Converts a Uri (e.g., from the gallery) into a File stored in the app's cache directory.
- Handles exceptions and ensures invalid URIs return null.

**Tests Added**

To ensure the reliability and accuracy of the new features, I implemented tests for all the new code, specially the function uriToFile. 
Finally we have a  91% test coverage with a wide range of unit and UI tests for the new and existing functionalities.

________
**Next Steps**

The next phase involves:
Integrating profile picture management into other screens, such as: ProfileScreen and FriendsListScreen.

________

Capture d’écran 2024-11-07 à 21 07 06

### CODE REVIEW

**Review by samymessouak — APPROVED** [review]
### Code Review

The code in this PR demonstrates strong quality and attention to detail:

- The modular approach to UI components, such as `UserProfilePicture` and `ActionButtons`, promotes **reusability and clarity**. This not only makes future modifications easier but also enhances the readability and maintainability of the code.
- The **effective use of State and Flow** (`collectAsState()`) ensures that the UI updates reactively, which is crucial for a seamless user experience.
- Error handling in the `uriToFile()` function is well-implemented, providing **robust safeguards** against potential crashes due to invalid URIs, which is a key aspect of reliable user input handling.
- Finally, adding appropriate `testTags` and covering functionalities with **91% test coverage** indicates a strong emphasis on **quality assurance** and a proactive approach to prevent future regressions.

Overall, this PR sets a good standard for modularity, usability, and maintainability in our codebase. Great work!

**Review by ziyadbagh — APPROVED** [review]
The photo functionality works as expected—I was able to select a photo from the library, and the test coverage is good. I'll approve this PR.

One note: when deleting a photo, the app automatically saves the change without requiring a click on the "Save" button.

**Comment by nada-ezziti** [comment]
> The photo functionality works as expected—I was able to select a photo from the library, and the test coverage is good.
> 
> One note: when deleting a photo, the app automatically saves the change without requiring a click on the "Save" button.

Nice catch. This is fixed now.

**Review by ziyadbagh — APPROVED** [review]
Great job! It’s working as expected now. I’ll go ahead and approve it.

**Pull request merged**
