### PR TITLE
feat: Add a web link to the ASL alphabet on the practice screen and format files

### PR DESCRIPTION
**Pull request by SaFouNaldo**
- Added the necessary imports such as Intent & Uri
 -  added a constant value that contains the Uri to the webpage
 - link the button to the webpage and launch it when the user click on it (a set of image that contains the ASL alphabet)
Related issue : #138

### CODE REVIEW

**Review by nada-ezziti — APPROVED** [review]
Nice work implementing the button to open the ASL alphabet image! Linking directly to a resource that enhances the user experience is a great addition.

To improve maintainability and follow best practices, it would be beneficial to move the hardcoded URL string to the strings.xml file. This allows for easier updates in the future and keeps the code clean. 

Overall, this is a valuable update, it’s good to merge!

**Comment by SaFouNaldo** [comment]
> Nice work implementing the button to open the ASL alphabet image! Linking directly to a resource that enhances the user experience is a great addition.
> 
> To improve maintainability and follow best practices, it would be beneficial to move the hardcoded URL string to the strings.xml file. This allows for easier updates in the future and keeps the code clean.
> 
> Overall, this is a valuable update, it’s good to merge!

I'll do that thanks for the feedback !

**Comment by ThomasMPont** [comment]
I've changed the title for your issue. In the future, try to clearly mention what parts of the projects your changes involve.

**Review by ThomasMPont — APPROVED** [review]
The link seems to work.
Low coverage on such a small change should be fine.
SonarCloud was raising 2 issues on typos within your URL, maybe it does not belong in a string resource. Remember to look out for Android Studio or SonarCloud warnings.

I see your commit messages do not all follow the same conventions. When you mess up a commit message, you can edit it using `git commit --amend` or `git reset --soft HEAD~N` before pushing to Github.

Nice work regardless. 👍

**Comment by ThomasMPont** [comment]
P.S. Try to avoid using short branch names, to avoid collisions and confusion.

**Pull request merged**
