### PR TITLE
Enhance Challenge Management and Lifecycle Support

### PR DESCRIPTION
**Pull request by samymessouak**
# What's New?

This PR introduces key enhancements to the challenge management system, improving functionality, simplifying the codebase, and ensuring robust integration with Firestore.

# Changes Made

- Game Mode Support: Added game mode functionality to the Challenge class, making challenges more dynamic and versatile.
- Refactored ChallengeRepository:
- Removed redundant methods.
- Introduced a new deleteChallenge function, now integrated into ChallengeViewModel for streamlined challenge management.
**Simplified User Class:**
- Removed outdated challenge management methods.
- Improved clarity and maintainability of the codebase.
- Enhanced UserViewModel:
- Added getOngoingChallenge and removeOngoingChallenge methods to better manage the challenge lifecycle.
- Manual End-to-End Testing: Verified all changes to ensure seamless functionality with Firestore and maintain system integrity.

# Why This Matters

These changes make the challenge system more dynamic, scalable, and easier to manage, improving the overall user experience and paving the way for future updates.

### CODE REVIEW

**Review by ThomasMPont — DISMISSED** [review]
I don't have the time for a comprehensive review right now, but I wanted to point out that your PR raises 3 SonarCloud issues. Could you try fixing them, so I can review an updated PR later?

**Comment by SaFouNaldo** [comment]
I can see that you :

- Added mode property to the Challenge data class for supporting game modes, enhancing challenge versatility.
### ChallengeRepository Refactor:

- Removed redundant methods (acceptChallenge, submitGesture, getChallengeUpdates).
- Introduced deleteChallenge for a more streamlined approach to challenge management.
### ChallengeRepositoryFirestore:

- Implemented deleteChallenge to allow removal of challenges from Firestore.
- Removed deprecated functions (acceptChallenge, submitGesture, getChallengeUpdates) to simplify the repository logic.
### ChallengeViewModel:

- Removed methods (acceptChallenge, submitGesture, getChallengeUpdates) that were no longer needed.
- Added deleteChallenge method for handling the deletion of challenges, ensuring ViewModel functionality aligns with repository changes.
### UserRepository and UserRepositoryFirestore:

- Replaced old methods like removeOngoingChallenge and addPastChallenge with getOngoingChallenges and refactored removeOngoingChallenge.
- The new getOngoingChallenges method retrieves all ongoing challenges for a user, fetching additional details for better UI representation.
### UserViewModel:

- Introduced _ongoingChallenges to store the list of ongoing challenges.
- Updated getOngoingChallenges to manage challenge retrieval within the ViewModel.
- Refactored removeOngoingChallenge to reflect recent changes, ensuring consistency in data handling.

The refactoring of ChallengeRepository and ChallengeViewModel to remove redundant methods greatly simplifies the codebase, making it easier to maintain.

This is a Solid PR but you will need to resolve the conflict (that shouldn't be hard ), you can directly modify it in Github

**Review by SaFouNaldo — APPROVED** [review]
See the comment below

**Review by NBCCF025 — APPROVED** [review]
As we are running late on time and the test are comming right after on other tasks I think it is not a big problem.

**Pull request merged**
