### PR TITLE
Refactor unauthenticated behavior of connected screens

### PR DESCRIPTION
**Pull request by ThomasMPont**
## Motivation

The current implementation for offline mode is brittle and insufficient.
Ideally,
- Screens should be the same for online, offline and unauthenticated users.
- Access to screens should be limited when unauthenticated.
- The user should be notified when a network call fails.
- The app should be robust to a user being logged out at any moment.
- The app should be robust to a user losing connectivity at any moment.

## Changes

From the list above, the following should hold,
- Screens should be the same for online, offline and unauthenticated users.
- Access to screens should be limited when unauthenticated.
- The app should be robust to a user being logged out at any moment.

### Offline mode

The recent offline mode implementation has partially been reverted. Instead of proceeding in offline mode, users now simply skip the login screen.
image
This allows the user to get as much use of the app as possible while not logged in.

Screens and top level destinations now hold an `requiresAuth` boolean, which restrict access to screens that require a logged in user. When an unauthenticated user tries to navigate to a screen which requires an account, they are displayed the following toast,
image

### Renaming

I've renamed and moved `Utils.WhiteOfflineScreen()` to `auth.UnauthenticatedScreen.kt`, as it is now used as a standalone screen.

### Fixes

`MainActivity.SignifyAppPreview()` no longer takes a `navigationState` parameter, as navigation should never be influenced from the outside.
A single test, `MainActivityTest.testNavigationFromMainActivityAndEveryScreenIsDisplayed()` was injecting a `NavigationState` into `MainActivity` for testing. This test was nonsense and redundant. I've deleted it entirely.
Here it is if you think there is something to salvage from it.
```kotlin
class MainActivityTest {
  @get:Rule val composeTestRule = createComposeRule()
  private val navigationState = MutableStateFlow<NavigationActions?>(null)
  private val navigationActions = mock(NavigationActions::class.java)
  private val userSession = MockUserSession()
  @get:Rule
  val cameraAccess: GrantPermissionRule = GrantPermissionRule.grant(Manifest.permission.CAMERA)

  @Before
  fun setUp() {
    val userRepository = mock(UserRepository::class.java)
    val statsRepository = mock(StatsRepository::class.java)
    val context = mock(Context::class.java)

    composeTestRule.setContent {
      isOfflineState = false
      FriendsListScreen(navigationActions, userSession, userRepository)
      SettingsScreen(navigationActions, userSession, userRepository)
      ProfileScreen(navigationActions, userSession, userRepository, statsRepository)
      MyStatsScreen(navigationActions, userSession, userRepository, statsRepository)

      // Set the content with the mocked context
      SignifyAppPreview(context, AppDependencyProvider, navigationState)
    }
  }

  @Test
  fun testNavigationFromMainActivityAndEveryScreenIsDisplayed() {

    composeTestRule.onNodeWithTag("WelcomeScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationActions.navigateTo(Screen.PROFILE) }
    composeTestRule.onNodeWithTag("ProfileScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.AUTH) }
    composeTestRule.onNodeWithTag("LoginScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationActions.navigateTo(Screen.FRIENDS) }
    composeTestRule.onNodeWithTag("FriendsListScreen").assertIsDisplayed()
    composeTestRule.onNodeWithContentDescription("Search").performClick()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.EXERCISE_EASY) }
    composeTestRule.onNodeWithTag("ExerciseScreenEasy").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.EXERCISE_MEDIUM) }
    composeTestRule.onNodeWithTag("ExerciseScreenMedium").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.EXERCISE_HARD) }
    composeTestRule.onNodeWithTag("ExerciseScreenHard").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationActions.navigateTo(Screen.SETTINGS) }
    composeTestRule.onNodeWithTag("SettingsScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.HOME) }
    composeTestRule.onNodeWithTag("HomeScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationActions.navigateTo(Screen.STATS) }
    composeTestRule.onNodeWithTag("MyStatsScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.CHALLENGE_HISTORY) }
    composeTestRule.onNodeWithTag("ChallengeHistoryScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.CHALLENGE) }
    composeTestRule.onNodeWithTag("ChallengeScreen").assertIsDisplayed()

    composeTestRule.runOnIdle { navigationState.value?.navigateTo(Screen.PRACTICE) }
  }
}
```

## Tests

I've written tests for `NavigationActions`, that I've changed, as it was somehow never tested.

I've also had to make minor changes to the `UnauthenticatedScreen`'s tests.

### Connectivity

The following must still be implemented,
- The user should be notified when a network call fails.
- The app should be robust to a user losing connectivity at any moment.

This implies changes to many of our connected features, and will probably be the subject of multiple tasks.

### Additional checks

While I have restricted navigation when unauthenticated, a user could get logged out while on an illegal screen, or circumvent these restrictions.
Currently, the behavior of connected features while logged out is undefined. For example, I was able to update my username on Firestore while logged out.
image
*Why is "unknown" even a user anyway?"*

Ideally, any account related features should be blocked when unauthenticated.

### Offline account usage

Currently, the behavior of the app while authenticated but offline is undefined.

Ideally, the app should either cache user actions. Alternatively, it should at least clearly notify the user that their actions are not being saved on the cloud.

### Login prompt

Perhaps, when an unauthenticated user tries to access an illegal screen, they should be prompted to log in by some popup.

### CODE REVIEW

**Review by SaFouNaldo — CHANGES_REQUESTED** [review]
**Changes Made:**  
1. Removed `userSession` as a parameter for the `LoginScreen`.  
2. Updated the button from `offlineMode` to `skipLogin`, restricting the app to only use the `HomeScreen` and `Practice`. Trying to access other features now displays a **Toast** message.  
3. Great fixes in the `MainActivity` to resolve issues with hardcoded parts, ensuring `navigationActions` are now handled outside the function.  
4. Other file changes align with these updates to maintain consistency.

**Request for Changes:**  
Instead of using a simple **Toast** for restricted access to important screens (like **Challenges** and **Profile**), we could use the `WhiteOfflineScreen` component I previously created. For less important features, keeping the **Toast** is fine, but implementing the `WhiteOfflineScreen` for critical screens would improve user experience and maintain consistency.

**Comment by ThomasMPont** [comment]
I realized that tests for `NavigationActions` were missing. I've been having a lot of trouble testing it. This might take me a while.

**Comment by ThomasMPont** [comment]
@SaFouNaldo 
> Request for Changes:
Instead of using a simple Toast for restricted access to important screens (like Challenges and Profile), we could use the WhiteOfflineScreen component I previously created. For less important features, keeping the Toast is fine, but implementing the WhiteOfflineScreen for critical screens would improve user experience and maintain consistency.

I've made main screens route to the `WhiteOfflineScreen()` now named `UnauthenticatedScreen()`.
As discussed in today's meeting, the missing tests for `NavigationActions.kt` will come in a later PR.

**Review by SaFouNaldo — APPROVED** [review]
Good job on taking into account what we discussed.

**Pull request merged**
